name: "Hello .NET"

on:
  workflow_dispatch:

env:
  TEST_PATH: Notes.Api.Test/Notes.Api.Test.csproj

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: "Dotnet Restore"
        run: "dotnet restore"
      - name: "Dotnet build"
        run: "dotnet build $TEST_PATH"
      - name: "Dotnet test"
        run: "dotnet test --no-build --configuration Release $TEST_PATH"
      # - name: "Dotnet run"
      #   run: "dotnet run"
      - name: "Print .NET CLI version"
        run: dotnet --version