name: "Hello .NET"

on:
  workflow_dispatch:

env:
  TEST_PROJ_PATH: Notes.Api.Test/Notes.Api.Test.csproj
  TEST_PATH: Notes.Api.Test/Notes.Api.Test

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: "Dotnet Restore"
        run: "dotnet restore $TEST_PROJ_PATH"
      - name: "Dotnet build"
        run: "dotnet build $TEST_PROJ_PATH"
      - name: "Dotnet test"
        run: "dotnet test --configuration Release $TEST_PROJ_PATH --logger trx"
      # - name: "Dotnet run"
      #   run: "dotnet run"
      - name: "Print .NET CLI version"
        run: dotnet --version
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Dotnet Tests            # Name of the check run which will be created
          path: $TEST_PATH/TestResults/*.trx    # Path to test results
          reporter: dotnet-trx